# Generated by Django 2.1 on 2020-03-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donateblood',
            name='slug',
        ),
    ]
