# Generated by Django 2.1 on 2020-03-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_remove_donateblood_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateblood',
            name='gender',
            field=models.CharField(default='male', max_length=20),
            preserve_default=False,
        ),
    ]
