# Generated by Django 2.1 on 2020-03-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_donateblood_author2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateblood',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
